name: Images

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:

  images:

    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-tags: 'master'
            zsh-ref: 'master'
          - docker-tags: |
              5.8
              latest
            zsh-ref: 'zsh-5.8'
          - docker-tags: '5.7.1'
            zsh-ref: 'zsh-5.7.1'
          - docker-tags: '5.7'
            zsh-ref: 'zsh-5.7'
          - docker-tags: '5.6.2'
            zsh-ref: 'zsh-5.6.2'
          - docker-tags: '5.6.1'
            zsh-ref: 'zsh-5.6.1'
          - docker-tags: '5.6'
            zsh-ref: 'zsh-5.6'
          - docker-tags: '5.5.1'
            zsh-ref: 'zsh-5.5.1'
          - docker-tags: '5.5'
            zsh-ref: 'zsh-5.5'
          - docker-tags: '5.4.2'
            zsh-ref: 'zsh-5.4.2'
          - docker-tags: '5.4.1'
            zsh-ref: '5.4.1'
          - docker-tags: '5.4'
            zsh-ref: '5.4'
          - docker-tags: '5.3.1'
            zsh-ref: 'zsh-5.3.1'
          - docker-tags: '5.3'
            zsh-ref: 'zsh-5.3'
          - docker-tags: '5.2'
            zsh-ref: 'zsh-5.2'
          - docker-tags: '5.1.1'
            zsh-ref: 'zsh-5.1.1'
          - docker-tags: '5.1'
            zsh-ref: 'zsh-5.1'
          - docker-tags: '5.0.8'
            zsh-ref: 'zsh-5.0.8'
          - docker-tags: '5.0.7'
            zsh-ref: 'zsh-5.0.7'
          - docker-tags: '5.0.6'
            zsh-ref: 'zsh-5.0.6'
          - docker-tags: '5.0.5'
            zsh-ref: 'zsh-5.0.5'
          - docker-tags: '5.0.4'
            zsh-ref: 'zsh-5.0.4'
          - docker-tags: '5.0.3'
            zsh-ref: 'zsh-5.0.3'
          - docker-tags: '5.0.2'
            zsh-ref: 'zsh-5.0.2'
          - docker-tags: '5.0.1'
            zsh-ref: 'zsh-5.0.1'
          - docker-tags: '5.0.0'
            zsh-ref: 'zsh-5.0.0'
          - docker-tags: '4.3.17'
            zsh-ref: 'zsh-4.3.17'
          - docker-tags: '4.3.16'
            zsh-ref: 'zsh-4.3.16'
          - docker-tags: '4.3.15'
            zsh-ref: 'zsh-4.3.15'
          - docker-tags: '4.3.14'
            zsh-ref: 'zsh-4.3.14'
          - docker-tags: '4.3.13'
            zsh-ref: 'zsh-4.3.13'
          - docker-tags: '4.3.12'
            zsh-ref: 'zsh-4.3.12'
          - docker-tags: '4.3.11'
            zsh-ref: 'zsh-4.3.11'


    name: ${{ matrix.docker-tags }}

    runs-on: 'ubuntu-latest'

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          use: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && matrix.zsh-ref != 'master'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.zsh-ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Github registry
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/multiarch-test' && github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: ${{ matrix.docker-tags }}
          labels: |
            maintainer=https://github.com/zsh-users
            org.opencontainers.image.title=zsh
            org.opencontainers.image.description=Zsh is a shell designed for interactive use, although it is also a powerful scripting language.
            org.opencontainers.image.url=https://www.zsh.org
            org.opencontainers.image.source=https://github.com/zsh-users/zsh-docker
            org.opencontainers.image.licenses=https://raw.githubusercontent.com/zsh-users/zsh/master/LICENCE

      - name: Build and push image
        uses: docker/build-push-action@v2
        timeout-minutes: 60
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/multiarch-test' && github.event_name != 'pull_request' }}
          build-args: ref=${{ matrix.zsh-ref }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # workaround for https://github.com/docker/build-push-action/issues/252 / https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  notify:
    runs-on: ubuntu-latest
    needs: images
    if: failure() && github.event_name != 'pull_request' && github.repository_owner == 'zsh-users'
    steps:
      - name: Send notification to Matrix channel
        id: matrix-chat-message
        uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: 'matrix.org'
          token: ${{ secrets.MATRIX_TOKEN }}
          channel: '!gWTEWHvypdUdiLeXET:matrix.org'
          message: |
            [Build ${{ github.run_id }} failed](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
